### ISSUE TITLE
Make TBLP a TGraphic in VCL

### ISSUE THREAD

**Issue by Memnarch** [Dennis1000/libblp#1]
While it's looking good, getting it displayed seems a bit cumbersome. Why not derive it from TGraphic(for VCL applications) and register the fileformat? Allows users to pick it when opening a picture in TImage or using TPicture.LoadFromFile.

Yes this will only display the High-Resultion Mipmap(0) but is way more easier for simple situation.

Maybe adding an overload to Draw-Method with a new parameter "MipMapLevel" to select the level when Drawing. At least when you are working explicitly with a TBLP, this will do the job.

Or derive TBLP from TGraphic, and give it an array of TMipMap(Based on TGraphic, too). WHen TBLP.Draw is used, it will paint MipMap-Level 0, but this allows to choose from the array when you need an Explicit level.

**Comment by Dennis1000** [comment]
TBLP started as a loader only library - the drawing part of TBLP was just done to simplify the verification of the loading part ...and to satisfy my curiosity about DXT compression / decompression ;-)
IMHO adding it to TGraphic as a fileformat does not really make sense because the BLP file format is a texture file format, the drawing should be done by the hardware graphics system (e.g. opengl) - not by slow software.
But feel free to extend it anytime - you're welcome ;-)

**Comment by Memnarch** [comment]
Okay fair enough ;)
